# Generated by Django 4.2.29 on 2026-03-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_category_alter_notes_description_notes_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
